### ISSUE TITLE
Standard RPDO padding not possible

### ISSUE THREAD

**Issue by nattgris** [rtlabs-com/c-open#11]
It seems standard RPDO padding between mappings as per CiA 301 §7.4.7.1 is not implemented.

For static mappings I guess you could work around it by defining objects like

``` c
	{0x0005, OTYPE_DEFTYPE,0,               OD0005, NULL},
```

with

``` c
static uint8_t dummy;

/* Entry descriptor for UNSIGNED8 (0005h) */
static const co_entry_t OD0005[] = {
	{0x00, OD_WO | OD_TRANSIENT | OD_RPDO, DTYPE_UNSIGNED8, 8, 0, &dummy},
};
```
However to support dynamic mappings you'd basically have to do this for all integer types for all slaves, because you don't know what mapping the master may set up. Seems better if that was built into the stack.

**Comment by hefloryd** [comment]
Agreed, padding using the static data types should be possible.

**Comment by hefloryd** [comment]
This PR adds support for padding. The CiA spec mentions padding for RPDO:s only, this PR would make it possible add padding into TPDO:s as well. It also doesn't validate the bitlength against the datatypes, as it seems useful to be able to e.g. pad 7 bits using a BOOLEAN datatype.
