### ISSUE TITLE
CiA 417 uses invalid PDO COB-ID

### ISSUE THREAD

**Issue by nattgris** [rtlabs-com/c-open#16]
While implementing CiA 417 object dictionary I noticed that RPDO 261 is specified (CiA 417:3 §A.1) as using COB-ID 0x180 but the stack is not accepting this. And indeed, looking at CiA 301 §7.3.5 that CAN-ID is listed as restricted, not for use by PDOs etc.

Now I wonder, is that a mistake/typo in the CiA 301 document and, by extension, in the stack? Or is it just a temporary loss of brain functionality when they picked COB-IDs for CiA 417?

Regardless, can the check in `co_validate_cob_id()` be relaxed to support the CiA 417 requirements?

**Comment by hefloryd** [comment]
We can relax it. Please send a PR and mention in e.g. a comment why the check does not follow CiA 301.
