### ISSUE TITLE
Automatic transition to NMT Pre-operational for non-critical errors

### ISSUE THREAD

**Issue by nattgris** [rtlabs-com/c-open#39]
The 1029h Error behavior object allows to configure whether the device should autonomously enter Pre-operational, Stopped or to remain in the current NMT state, after a "serious CANopen device failure". The default behavior, and the only behavior if 1029h is not implemented, is to transition to Pre-operational.

This is implemented correctly by the stack, however the transition (if not disabled) is taken regardless of which error has occurred, for any EMCY that is sent by the application. CiA301 lists the following conditions as mandatory for being "CANopen device failures":

- Bus-off
- Life guarding or Heartbeat time-out

"Severe CANopen device errors also may be caused by CANopen device internal failures". But there is no way to tell that a specific EMCY is not considered severe by the application.

**Comment by hefloryd** [comment]
Perhaps there should be a list of error codes (or code classes) that are considered severe errors. For instance 81xx would cover the mandatory conditions. 

Another method could be to abuse the info argument to co_emcy_tx so that say bit 31 is used to indicate severe error. Info is manufacturer specific and ends up in the error history.

**Comment by nattgris** [comment]
Perhaps the default behavior should be to only change NMT state for the mandatory events. After all it's not necessary to do it for any other events. If someone needs the behavior for specific EMCY events, maybe that could be hacked in later, using an argument to co_emcy_tx or some compile time configuration. I can sent a PR for this.

However, an additional problem is that for the bus-off event, I suspect that the NMT change is supposed to happen at the actual bus-off event, not after some future bus-off recovery when the bus-off-recovered EMCY 0x8140 is sent. Even if the automatic NMT change won't be visible over the bus, profiles such as CiA402 may connect profile specific behavior to the NMT state change, to handle loss of communication in a safe way etc. Delaying that until communication is restored I think misses the point.
