### ISSUE TITLE
SDO abort codes not exported

### ISSUE THREAD

**Issue by nattgris** [rtlabs-com/c-open#9]
The public `co_api` header defines the `co_access_fn` function type. But when implementing such an access function, you probably need one or more of the `CO_SDO_ABORT` codes which are only defined in the private `co_sdo` header.

**Comment by hefloryd** [comment]
Good point, they should be moved to the public header.

**Comment by hefloryd** [comment]
See PR #10. Additionally `co_access_fn` should probably return `co_sdo_abort_t` instead of `uint32_t`.
